name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:   # 👈 запускать только вручную (кнопка в Actions)

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest       # Среда, где запускается job — Ubuntu Linux
    name: Build and Deploy Job   # Имя job, видно в Actions
    steps:
      - uses: actions/checkout@v3   # ⬇️ Клонирует твой репозиторий в раннер
        with:
          submodules: true          # Если в проекте есть git submodules — подтянет их
          lfs: false                # Git LFS (большие файлы). false = не использовать

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1  # ⬇️ Официальный action Azure SWA для деплоя
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MUD_0DEE66A03 }} 
          # 🔑 Секретный токен, чтобы GitHub мог заливать файлы в Azure

          repo_token: ${{ secrets.GITHUB_TOKEN }}  
          # 🔑 Стандартный GitHub-токен (для комментариев в PR и интеграций)

          action: "upload"  
          # 📦 Команда для action: "upload" = собрать и загрузить фронт в SWA

          # ==============================
          # 🔧 Настройки сборки проекта
          # ==============================

          app_location: "./client"   # 📂 Путь к фронтенду в репозитории
          api_location: ""           # 📂 Путь к API (у тебя бэкенд отдельно → оставляем пустым)
          output_location: "dist"    # 📂 Папка с результатом билда (vite build → client/dist)
